<?php

$plugin = array(
  'title' => t('Bootstrap facttic site template'),
  'theme' => 'bootstrap_facttic_site_template',
  'icon' => 'bootstrap-facttic-site-template.png',
  'category' => 'Bootstrap facttic',
  'regions' => array(
    'logo' => t('Logo'),
    'search'=> t('Search'),
    'branding' => t('Branding'),
    'nav' => t('Navigation'),
    'main' => t('Main'),
    'interest_links' => t('Interest links'),
    'members' => t('Members'),
    'footer' => t('Footer'),
  ),
);

