JTA_I18N.addResourceBundle('jTweetsAnywhere', 'es',
{
	'More': 'Cargar M&aacute;s',
	'Prev': 'Anterior',
	'Next': 'Siguiente',
	'%count% new tweet': '%count% nuevo Tweet',
	'%count% new tweets': '%count% nuevos Tweets',
	"What's happening?": "Que esta pasando?",
	'%secs% second ago': 'hace %secs% Segundo',
	'%secs% seconds ago': 'hace %secs% Segundos',
	'%mins% minute ago': 'jace %mins% Minuto',
	'%mins% minutes ago': 'hace %mins% Minutos',
	'%hours% hour ago': 'hace %hours% Hora',
	'%hours% hours ago': 'hace %hours% Horas',
	'%days% day ago': 'hace %days% Dia',
	'%days% days ago': 'hace %days% Dias',
	'via': 'via',
	'on Twitter': 'en Twitter',
	'Reply': 'Responder',
	'Retweet': 'Retwitear',
	'Favorite': 'Agregar a favoritos',
	'here': 'aqui',
	'in reply to': 'en respuesta a',
	'from': 'de',
	' and %rtc% other': ' y %rtc% mas',
	' and %rtc% others': ' y %rtc% mas',
	'Retweeted by': 'Retwiteado por',
	'Sign out': 'Cerrar sesi&oacute;n',
	'loading': 'cargando',
	'ERROR': 'ERROR',

	'$$monthNames': [ "Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic" ]
});
