<?php

/**
 * Implements hook_panels_layouts().
 */
// Plugin definition
$plugin = array(
  'title' => t('home-comunidad'),
  'category' => t('Comunidad resellers'),
  'icon' => 'home-comunidad.png',
  'theme' => 'home-comunidad',
  'regions' => array(
    'slider' => t('Slider'),
    'datos-usuario' => t('Datos del usuario'),
    'categoria-usuario' => t('Categoria del usuario'),
    'banner1' => t('Banner'),
    'banner2' => t('Banner'),
    'banner3' => t('Banner'),
    'banner4' => t('Banner'),
    'banner5' => t('Banner'),
    'banner6' => t('Banner'),
    'banner7' => t('Banner'),
    'banner8' => t('Banner'),
    'banner9' => t('Banner'),
    'banner10' => t('Banner'),
    'contacto' => t('Contacto'),
  ),
);
